config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:show, :index, :destroy ] do
    collection do
      post :invite
    end
  end
  root 'welcome#index'
  get 'home', to: 'pages#index' 
  resources :projects do
    resources :project_users, only: [:index, :destroy] do
      collection do
        post :invite
      end
    end
    resources :teams do
      resources :project_users, only: [:destroy]
    end
    resources :epics
    resources :issues
  end
end

app/models/user_story.rb
class UserStory < ApplicationRecord
  belongs_to :epic
  has_many :tasks

  validates :name, presence: true,
             uniqueness: { scope: :epic_id, case_sensitive: false }
  validates :priority, presence: true, uniqueness: { scope: :epic_id }, allow_blank: true

  # Tutaj wchodzi kwestia przypisania, chciałbym żeby była liczona ilość
  # user storiesów w zależności od przynależności do projektu, a nie że
  # zlicza zakres w zależności od ogólnej ilości recordów danego modelu
  # i tu wchodzi większa rozkmina, w której chyba trzeba będzie trochę
  # zmienić rodzaj przypisania
  def self.priority_range
    # Pobierz ilość rekordów w bazie danych
    record_count = count
    # Utwórz zakres od 1 do ilości rekordów
    (1..record_count).to_a
  end
end

app/views/user_stories/show/_breadcrumb.html.slim
nav.flex.mb-5[aria-label="Breadcrumb"]
  ol.inline-flex.items-center.space-x-1.text-sm.font-medium.md:space-x-2
    li.inline-flex.items-center
      = link_to projects_path, class: 'inline-flex items-center text-gray-700 hover:text-primary-600 dark:text-gray-300 dark:hover:text-white' do 
        svg[width="18" height="18" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"]
          path[d="M21.728 12.686C19.348 14.942 15.575 16.067 11.853 16.067C8.131 16.067 4.453 14.941 2.282 12.696L2 12.437V20C2 20.5304 2.21071 21.0391 2.58579 21.4142C2.96086 21.7893 3.46957 22 4 22H20C20.5304 22 21.0391 21.7893 21.4142 21.4142C21.7893 21.0391 22 20.5304 22 20V12.4L21.728 12.686Z" fill="#2F2F38"]
          path[d="M2.135 9.847L3.677 11.264C7.277 14.976 16.424 14.964 20.312 11.274L21.605 9.9C21.7148 9.78678 21.8503 9.70171 22 9.652V8C22 7.46957 21.7893 6.96086 21.4142 6.58579C21.0391 6.21071 20.5304 6 20 6H17V5C17 4.20435 16.6839 3.44129 16.1213 2.87868C15.5587 2.31607 14.7956 2 14 2H10C9.20435 2 8.44129 2.31607 7.87868 2.87868C7.31607 3.44129 7 4.20435 7 5V6H4C3.46957 6 2.96086 6.21071 2.58579 6.58579C2.21071 6.96086 2 7.46957 2 8V9.765C2.04703 9.78885 2.09216 9.81626 2.135 9.847ZM12 12.25C11.7528 12.25 11.5111 12.1767 11.3055 12.0393C11.1 11.902 10.9398 11.7068 10.8452 11.4784C10.7505 11.2499 10.7258 10.9986 10.774 10.7561C10.8222 10.5137 10.9413 10.2909 11.1161 10.1161C11.2909 9.9413 11.5137 9.82225 11.7561 9.77402C11.9986 9.72579 12.2499 9.75054 12.4784 9.84515C12.7068 9.93976 12.902 10.1 13.0393 10.3055C13.1767 10.5111 13.25 10.7528 13.25 11C13.25 11.3315 13.1183 11.6495 12.8839 11.8839C12.6495 12.1183 12.3315 12.25 12 12.25ZM9 5C9 4.73478 9.10536 4.48043 9.29289 4.29289C9.48043 4.10536 9.73478 4 10 4H14C14.2652 4 14.5196 4.10536 14.7071 4.29289C14.8946 4.48043 15 4.73478 15 5V6H9V5Z" fill="#2F2F38"]
        .ml-1
          | Projects
    li.flex.items-center
      svg.w-6.h-6.text-gray-400[fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"]
      = link_to "#{@user_story.epic.project.name}", project_path(@user_story.epic.project) , class: 'ml-1 text-gray-700 hover:text-primary-600 md:ml-2 dark:text-gray-300 dark:hover:text-white'
    li.flex.items-center
      svg.w-6.h-6.text-gray-400[fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
        path[fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"]
      = link_to "#{@user_story.epic.name}", epic_path(@user_story.epic), class: 'ml-1 text-gray-700 hover:text-primary-600 md:ml-2 dark:text-gray-300 dark:hover:text-white'
    li.flex.items-center
        svg.w-6.h-6.text-gray-400[fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
          path[fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"]
        span.ml-1.text-gray-400.md:ml-2.dark:text-gray-500[aria-current="page"]
          = @user_story.name

app/views/user_stories/show/_details_card.slim
.col-span-full.xl:col-auto.xl:pr-8
  .p-4.mb-4.bg-white.border.border-gray-200.rounded-lg.shadow-sm.2xl:col-span-2.dark:border-gray-700.sm:p-6.dark:bg-gray-800
    .items-center.sm:flex.xl:block.2xl:flex.sm:space-x-4.xl:space-x-0.2xl:space-x-4
      h3.mb-4.text-xl.font-semibold.dark:text-white
        | Details:
    .grid.grid-cols-6.gap-6
      .col-span-6.sm:col-span-3.text-sm.font-bold
          | Assignee:
      .col-span-6.sm:col-span-3.text-sm
          | Placeholder
      .col-span-6.sm:col-span-3.text-sm.font-bold
          | Labels:
      .col-span-6.sm:col-span-3.text-sm
          | Placeholder
      .col-span-6.sm:col-span-3.text-sm.font-bold
          | Sprint:
      .col-span-6.sm:col-span-3.text-sm
          | Placeholder
      .col-span-6.sm:col-span-3.text-sm.font-bold
          | Story point estimate 
      .col-span-6.sm:col-span-3.text-sm
          | Placeholder
      .col-span-6.sm:col-span-3.text-sm.font-bold
          | Reporter:
      .col-span-6.sm:col-span-3.text-sm
          | Placeholder
  .text-xs
    | Created 
    = time_ago_in_words(@user_story.created_at)
    |  ago
  .text-xs
    | Updated 
    = time_ago_in_words(@user_story.updated_at)
    |  ago

app/views/user_stories/show/_topbar_card.html.slim
.flex.justify-between.md:space-x-3.flex-shrink-0
  h1.text-xl.font-semibold.text-gray-900.sm:text-2xl.dark:text-white
    = @user_story.name
    button.mx-3.text-sm.rounded-full.md:mr-0.focus:ring-4.focus:ring-gray-300.dark:focus:ring-gray-600[type="button" aria-expanded="false" data-dropdown-toggle="dropdown-user_story"]
      span.sr-only
        | Open toolbar menu
      svg[width="20" height="20" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"]
        path[d="M19.4339 8.235C19.2825 7.86944 19.0262 7.55698 18.6972 7.33715C18.3683 7.11731 17.9815 6.99998 17.5859 7H6.41388C6.01838 7.00008 5.63178 7.11743 5.30296 7.3372C4.97414 7.55697 4.71786 7.86929 4.56652 8.23469C4.41518 8.60009 4.37558 9.00216 4.45271 9.39006C4.52985 9.77797 4.72026 10.1343 4.99988 10.414L10.5859 16C10.9609 16.3749 11.4696 16.5856 11.9999 16.5856C12.5302 16.5856 13.0388 16.3749 13.4139 16L18.9999 10.414C19.2795 10.1344 19.47 9.77816 19.5473 9.39031C19.6245 9.00246 19.5851 8.60042 19.4339 8.235Z" fill="#2F2F38"]
    #dropdown-user_story.hidden.z-50.my-4.w-56.text-base.list-none.bg-white.rounded.divide-y.divide-gray-100.shadow.dark:bg-gray-700.dark:divide-gray-600.rounded-xl
      ul.py-1.text-gray-700.dark:text-gray-300[aria-labelledby="dropdown"]
        li.border-b = link_to 'Edit', edit_user_story_path, class: "block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
        li = link_to 'Delete', user_story_path, class: "block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
  .hidden.xl:block
    .flex.items-center.space-x-3.w-full.md:w-auto.xl:pr-8
      = link_to edit_epic_path, class: "#{edit_btn_css} " do
        svg.w-5.h-5.mr-2[aria-hidden="true" fill="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
          path[d="M15.835 9.57801L15.83 9.58501L8.693 16.722L10.832 18.86L17.975 11.718L15.835 9.57801Z"]
          path[d="M5.139 13.168L7.278 15.308L14.416 8.17101L14.423 8.16601L12.282 6.02501L5.139 13.168Z"]
          path[d="M6.572 17.429L4 14.852L2.051 20.684C2.00093 20.8343 1.9873 20.9944 2.01123 21.1511C2.03516 21.3077 2.09597 21.4564 2.18865 21.5849C2.28133 21.7134 2.40323 21.8181 2.54429 21.8903C2.68535 21.9624 2.84154 22 3 22C3.10746 22.0001 3.21421 21.9825 3.316 21.948L9.147 20L6.572 17.429Z"]
          path[d="M20.821 3.17901C20.0654 2.4254 19.0417 2.0022 17.9745 2.0022C16.9073 2.0022 15.8836 2.4254 15.128 3.17901L13.7 4.61101L19.389 10.3L20.821 8.86801C21.5739 8.11279 21.9966 7.08989 21.9966 6.02351C21.9966 4.95712 21.5739 3.93423 20.821 3.17901Z"]
        | Edit
      = link_to epic_path, class: "#{delete_btn_css}", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do 
        svg.w-5.h-5.mr-2[aria-hidden="true" fill="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
          path[d="M20 6H16V4C16 3.46957 15.7893 2.96086 15.4142 2.58579C15.0391 2.21071 14.5304 2 14 2H10C9.46957 2 8.96086 2.21071 8.58579 2.58579C8.21071 2.96086 8 3.46957 8 4V6H4C3.73478 6 3.48043 6.10536 3.29289 6.29289C3.10536 6.48043 3 6.73478 3 7C3 7.26522 3.10536 7.51957 3.29289 7.70711C3.48043 7.89464 3.73478 8 4 8H5V20C5 20.5304 5.21071 21.0391 5.58579 21.4142C5.96086 21.7893 6.46957 22 7 22H17C17.5304 22 18.0391 21.7893 18.4142 21.4142C18.7893 21.0391 19 20.5304 19 20V8H20C20.2652 8 20.5196 7.89464 20.7071 7.70711C20.8946 7.51957 21 7.26522 21 7C21 6.73478 20.8946 6.48043 20.7071 6.29289C20.5196 6.10536 20.2652 6 20 6ZM10 4H14V6H10V4ZM11 18C11 18.2652 10.8946 18.5196 10.7071 18.7071C10.5196 18.8946 10.2652 19 10 19C9.73478 19 9.48043 18.8946 9.29289 18.7071C9.10536 18.5196 9 18.2652 9 18V10C9 9.73478 9.10536 9.48043 9.29289 9.29289C9.48043 9.10536 9.73478 9 10 9C10.2652 9 10.5196 9.10536 10.7071 9.29289C10.8946 9.48043 11 9.73478 11 10V18ZM15 18C15 18.2652 14.8946 18.5196 14.7071 18.7071C14.5196 18.8946 14.2652 19 14 19C13.7348 19 13.4804 18.8946 13.2929 18.7071C13.1054 18.5196 13 18.2652 13 18V10C13 9.73478 13.1054 9.48043 13.2929 9.29289C13.4804 9.10536 13.7348 9 14 9C14.2652 9 14.5196 9.10536 14.7071 9.29289C14.8946 9.48043 15 9.73478 15 10V18Z"]
        |Delete    