config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:show, :index, :destroy ] do
    collection do
      post :invite
    end
  end
  root 'welcome#index'
  get 'home', to: 'pages#index' 
  resources :projects do
    resources :project_users, only: [:index, :destroy] do
      collection do
        post :invite
      end
    end
    resources :teams do
      resources :project_users, only: [:destroy]
    end
    resources :epics
    resources :issues
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :project
  belongs_to :epic, optional: true
  # has_many :issue_users, dependent: :destroy
  # has_many :users, through: :issue_users
  # belongs_to :author, class_name: 'User', foreign_key: 'author_id', optional: true
  # has_many :tasks

  validates :name, presence: true,
             uniqueness: { scope: :epic_id, case_sensitive: false }
  validates :priority, presence: true, uniqueness: { scope: :epic_id }, allow_blank: true

  # Tutaj wchodzi kwestia przypisania, chciałbym żeby była liczona ilość
  # user storiesów w zależności od przynależności do projektu, a nie że
  # zlicza zakres w zależności od ogólnej ilości recordów danego modelu
  # i tu wchodzi większa rozkmina, w której chyba trzeba będzie trochę
  # zmienić rodzaj przypisania
  def self.priority_range
    # Pobierz ilość rekordów w bazie danych
    record_count = count
    # Utwórz zakres od 1 do ilości rekordów
    (1..record_count).to_a
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_project
  before_action :set_issue, only: %i[show edit update destroy]

  def index
    @issues = @project.issues.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @issue = @project.issues.new
  end

  def create
    @issue = @project.issues.new(issue_params)
    @issue.author = current_user
    if @issue.save
      @issue.issue_users.create(user: current_user)
      flash[:notice] = 'Issue was successfully created'
      redirect_to project_issue_path(@project, @issue)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @issue.update(issue_params)
      flash[:notice] = 'Issue was successfully updated'
      redirect_to project_issue_path(@project, @issue)
    else
      render :edit
    end
  end

  def destroy
    @issue.destroy
    redirect_to project_issues_path(@project)
  end

  private

  def set_issue
    @issue = @project.issues.find_by(id: params[:id])
    return unless @issue.nil?

    flash[:alert] = "This issue dosn't exist in this project"
    redirect_to project_issues_path(@project)
  end

  def issue_params
    params.require(:issue).permit(:name,
                                  :description,
                                  :epic_id,
                                  :status,
                                  :priority)
  end
end

app/views/issues/_form.html.slim
.max-w-2xl.m-auto
  = render 'shared/errors_validation', obj: @issue

section
  .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto
    .w-full.bg-white.border.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
      .p-6.space-y-4.md:space-y-6.sm:p-8
        h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
          = @issue.new_record? ? "Create a new user story" : "Edit user story"
        = form_with model: [@project, @issue], data: { turbo: false } do |form|
          .space-y-4.md:space-y-6
            .
              = form.label :name, class:"#{form_label_css}" 
              = form.text_field :name, autofocus: true, class:"#{text_field_input_css}", placeholder:"User story name" 
            .
              = form.label :description, class:"#{form_label_css}" 
              = form.text_area :description, rows:3, class:"#{form_text_area_input_css}", placeholder:"Description..." 
            .
              = form.label :epic, class:"#{form_label_css}" 
              = form.select :epic_id, epics_for_select, { prompt: "Select epic"}, { class: "#{form_select_input_css}" }
            .
              = form.label :status, class:"#{form_label_css}" 
              = form.select :status, ['active', 'suspended', 'ended'], {prompt: "Select status"}, {class:"#{form_select_input_css}" }
            .
              = form.label :priority, class:"#{form_label_css}" 
              = form.select :priority, Issue.priority_range, {prompt: "Select priority"}, {class:"#{form_select_input_css}" }
            .
              = form.submit (@issue.new_record? ? "Create user story" : "Update user story"), class:"#{form_submit_btn_css}" 
              = link_to "Back", project_issues_path, class:"#{form_back_btn_css} mt-4"

app/views/issues/_issues_list.html.slim
section.dark:bg-gray-900.p-3.sm:p-5
  .mx-auto.md:mx-8.border.rounded-lg.shadow
    .bg-white.dark:bg-gray-800.relative.shadow-md.sm:rounded-lg
      .flex.flex-col.md:flex-row.items-center.justify-between.space-y-3.md:space-y-0.md:space-x-4.p-4
        .w-full.md:w-auto
          = link_to new_project_issue_path, class:"#{create_btn_css} px-8" do
            svg.h-3.5.w-3.5.mr-2[fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"]
              path[clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"]
            | Add issue
      .overflow-x-auto
        table.w-full.text-sm.text-left.text-gray-500.border.dark:text-gray-400
          thead.text-xs.text-gray-700.uppercase.bg-gray-100.dark:bg-gray-700.dark:text-gray-400
            tr
              th.px-4.py-3[scope="col"]
                | User story name
              th.px-4.py-3[scope="col"]
                | Epic
              th.px-4.py-3[scope="col"]
                | Status
              th.px-4.py-3[scope="col"]
                | Priority
              th.px-4.py-3[scope="col"]
                | Owner
              th.px-4.py-3[scope="col"]
                | Actions
          tbody
            - @issues.each do |issue|
              tr.border-b.dark:border-gray-700
                th.px-4.py-3.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]
                  = link_to issue.name, project_issue_path(@project, issue)
                - unless issue.epic.nil?   
                  td.px-4.py-3.truncate
                    = link_to issue.epic.name, project_epic_path(@project, issue.epic)
                - else
                  td.px-4.py-3.truncate
                    | 
                td.px-4.py-3
                  = issue.status
                td.px-4.py-3
                  = issue.priority
                td.px-4.py-3
                  | Placeholder
                td.px-4.py-3.flex.items-center.justify-end
                  button id="#{issue.id}-dropdown-button" class="inline-flex items-center p-0 5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" data-dropdown-toggle="#{issue.id}-dropdown" type="button"
                    svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
                      path[d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"]
                  div id="#{issue.id}-dropdown" class=" hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                    div class= "py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="#{issue.id}-dropdown-button"
                      = link_to 'Show', project_issue_path(@project, issue), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to 'Edit', edit_project_issue_path(@project, issue), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to "Delete", project_issue_path(@project, issue), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
      nav.flex.flex-col.md:flex-row.justify-between.items-start.md:items-center.space-y-3.md:space-y-0.p-4
          = will_paginate @issues

app/views/issues/edit.html.slim
= render 'issues/form'

app/views/issues/index.html.slim
= render 'issues/issues_list'

app/views/issues/new.html.slim
= render 'issues/form'

app/views/issues/show.html.slim
.grid.grid-cols-1.px-4.pt-6.xl:grid-cols-3.xl:gap-4.dark:bg-gray-900
  .mb-4.col-span-full.xl:mb-2
    /Topbar_card
    = render partial: 'issues/show/breadcrumb'
    = render partial: 'issues/show/topbar_card'
  / Description & task_table
  .col-span-2
    .pt-4.mb-8.bg-white.col-span-2.dark:border-gray-700.dark:bg-gray-800
      .mb-4.text-lg.font-semibold.dark:text-white
        | Description:
      .text-sm
        = @issue.description
    /Task_table
    .pt-4.mb-4.bg-white.col-span-2.dark:border-gray-700.dark:bg-gray-800
      .mb-4.text-lg.font-semibold.dark:text-white
        | Tasks:
      .overflow-x-auto.pr-10
        table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
          tbody
            tr.border-t.border-b.dark:border-gray-700
              th.pl-4.md:pr-60.py-3.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]
                = link_to 'Future feature'
              td.px-4.py-3.flex.items-center.justify-end
                button id="#story-dropdown-button" class="inline-flex items-center p-0 5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" data-dropdown-toggle="#story-dropdown" type="button"
                  svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
                    path[d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"]
                div id="#story-dropdown" class=" hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                  div class= "py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="#story-dropdown-button"
                    = link_to 'Show', '#', class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                  .py-1
                    = link_to 'Edit', '#', class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                  .py-1
                    = link_to "Delete", '#', class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
  /Details_card
  = render partial: 'issues/show/details_card'