config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:show, :index, :destroy ] do
    collection do
      post :invite
    end
  end
  root 'welcome#index'
  get 'home', to: 'pages#index' 
  resources :projects do
    resources :project_users, only: [:index, :destroy] do
      collection do
        post :invite
      end
    end
    resources :teams do
      resources :project_users, only: [:destroy]
    end
    resources :epics
    resources :issues
  end
end

app/models/epic.rb
class Epic < ApplicationRecord
  include Timeable
  include Status
  belongs_to :project
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', optional: true
  # has_many :issues, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: { scope: :project_id, case_sensitive: false }
  validate :start_date_less_than_end_date?
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController

  before_action :set_project
  before_action :set_epic, only: %i[show edit update destroy]

  def index
    @epics = @project.epics.paginate(page: params[:page], per_page: 5)
  end

  def show
    @issues = Issue.where(epic: @epic)
  end

  def new
    @epic = @project.epics.new
  end

  def create
    @epic = @project.epics.new(epic_params)
    @epic.author = current_user
    if @epic.save
      flash[:notice] = 'Epic was successfully created'
      redirect_to project_epic_path(@project, @epic)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @epic.update(epic_params)
      flash[:notice] = 'Epic was successfully updated'
      redirect_to project_epic_path(@project, @epic)
    else
      render :edit
    end
  end

  def destroy
    @epic.destroy
    redirect_to project_epics_path
  end

  private

  def set_epic
    @epic = @project.epics.find_by(id: params[:id])
    return unless @epic.nil?

    flash[:alert] = "This epic doesn't exist in this project"
    redirect_to project_epics_path(@project)
  end

  def epic_params
    params.require(:epic).permit(:name,
                                 :description,
                                 :project_id,
                                 :status,
                                 :start_date,
                                 :end_date)
  end
end

app/views/epics/_epics_list.html.slim
section.dark:bg-gray-900.p-3.sm:p-5
  .mx-auto.md:mx-8.border.rounded-lg.shadow
    .bg-white.dark:bg-gray-800.relative.shadow-md.sm:rounded-lg
      .flex.flex-col.md:flex-row.items-center.justify-between.space-y-3.md:space-y-0.md:space-x-4.p-4
        .w-full.md:w-auto
          = link_to new_project_epic_path, class:"#{create_btn_css} pl-4 pr-6" do
            svg.h-3.5.w-3.5.mr-2[fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"]
              path[clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"]
            |  Add epic
      .overflow-x-auto
        table.w-full.text-sm.text-left.text-gray-500.border.dark:text-gray-400
          thead.text-xs.text-gray-700.uppercase.bg-gray-100.dark:bg-gray-700.dark:text-gray-400
            tr
              th.px-4.py-3[scope="col"]
                | Epic name
              th.px-4.py-3[scope="col"]
                | Status
              th.px-4.py-3[scope="col"]
                | Start date
              th.px-4.py-3[scope="col"]
                | End date
              th.px-4.py-3[scope="col"]
                | Owner
              th.px-4.py-3[scope="col"]
                | Actions
          tbody
            - @epics.each do |epic|
              tr.border-b.dark:border-gray-700
                th.px-4.py-3.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]
                  = link_to epic.name, project_epic_path(@project, epic)
                td.px-4.py-3
                  = epic.status
                td.px-4.py-3
                  = epic.start_date
                td.px-4.py-3
                  = epic.end_date                  
                td.px-4.py-3
                  | Placeholder
                td.px-4.py-3.flex.items-center.justify-end
                  button id="#{epic.id}-dropdown-button" class="inline-flex items-center p-0 5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" data-dropdown-toggle="#{epic.id}-dropdown" type="button"
                    svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
                      path[d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"]
                  div id="#{epic.id}-dropdown" class=" hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                    div class= "py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="#{epic.id}-dropdown-button"
                      = link_to 'Show', project_epic_path(@project, epic), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to 'Edit', edit_project_epic_path(@project, epic), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to "Delete", project_epic_path(@project, epic), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
      nav.flex.flex-col.md:flex-row.justify-between.items-start.md:items-center.space-y-3.md:space-y-0.p-4
          = will_paginate @epics

app/views/epics/_form.html.slim
.max-w-2xl.m-auto
  = render 'shared/errors_validation', obj: @epic

section
  .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto
    .w-full.bg-white.border.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
      .p-6.space-y-4.md:space-y-6.sm:p-8
        h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
          = @epic.new_record? ? "Create a new epic" : "Edit epic"
        = form_with model: [@project, @epic], data: { turbo: false } do |form|
          .space-y-4.md:space-y-6
            .
              = form.label :name, class:"#{form_label_css}" 
              = form.text_field :name, autofocus: true, class:"#{text_field_input_css}", placeholder:"Epic name" 
            .
              = form.label :description, class:"#{form_label_css}" 
              = form.text_area :description, rows:3, class:"#{form_text_area_input_css}", placeholder:"Description..." 
            .
              = form.label :project, class:"#{form_label_css}" 
              = form.select :project_id, projects_for_select, { prompt: "Select project"}, { class: "#{form_select_input_css}" }
            .
              = form.label :status, class:"#{form_label_css}" 
              = form.select :status, ['active', 'suspended', 'ended'], {prompt: "Select status"}, {class:"#{form_select_input_css}" }
            .            
              = form.label :start_date, class:"#{form_label_css}" 
              = form.date_select :start_date, {}, {class:"#{form_date_select_input_css}" } 
            .
              = form.label :end_date, class:"#{form_label_css}"
              = form.date_select :end_date, {}, {class:"#{form_date_select_input_css}" } 
            .
              = form.submit (@epic.new_record? ? "Create epic" : "Update epic"), class:"#{form_submit_btn_css}" 
              = link_to "Back", project_epics_path, class:"#{form_back_btn_css} mt-4" 

app/views/epics/edit.html.slim
= render 'epics/form'

app/views/epics/index.html.slim
= render 'epics/epics_list'

app/views/epics/new.html.slim
= render 'epics/form'

app/views/epics/show.html.slim
.grid.grid-cols-1.px-4.pt-6.xl:grid-cols-3.xl:gap-4.dark:bg-gray-900
  /Topbar_card
  .mb-4.col-span-full.xl:mb-2
    = render partial: 'epics/show/breadcrumb'
    = render partial: 'epics/show/topbar_card'
  / Description & issue_table
  .col-span-2
    .pt-4.mb-4.bg-white.col-span-2.dark:border-gray-700.dark:bg-gray-800
      .mb-4.text-lg.font-semibold.dark:text-white
        | Description:
      .text-sm
        = @epic.description  
    /Issue_table
    .pt-4.mb-4.bg-white.col-span-2.dark:border-gray-700.dark:bg-gray-800
      .flex.justify-between  
        .mb-4.text-lg.font-semibold.dark:text-white
          | User Stories:
        .flex.pl-2.space-x-1.mr-10
          = link_to "#", class: "inline-flex justify-center p-1 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" do
            svg.w-5.h-5[fill="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
              path[fill-rule="evenodd" d="M20 11H13V4C13 3.73478 12.8946 3.48043 12.7071 3.29289C12.5196 3.10536 12.2652 3 12 3C11.7348 3 11.4804 3.10536 11.2929 3.29289C11.1054 3.48043 11 3.73478 11 4V11H4C3.73478 11 3.48043 11.1054 3.29289 11.2929C3.10536 11.4804 3 11.7348 3 12C3 12.2652 3.10536 12.5196 3.29289 12.7071C3.48043 12.8946 3.73478 13 4 13H11V20C11 20.2652 11.1054 20.5196 11.2929 20.7071C11.4804 20.8946 11.7348 21 12 21C12.2652 21 12.5196 20.8946 12.7071 20.7071C12.8946 20.5196 13 20.2652 13 20V13H20C20.2652 13 20.5196 12.8946 20.7071 12.7071C20.8946 12.5196 21 12.2652 21 12C21 11.7348 20.8946 11.4804 20.7071 11.2929C20.5196 11.1054 20.2652 11 20 11Z"]
      .overflow-x-auto.pr-10
        table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400
          tbody
            - @issues.each do |issue|
              tr.border-t.border-b.dark:border-gray-700
                th.pl-4.md:pr-60.py-3.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]
                  = link_to issue.name, project_issue_path(@project, issue)
                td.px-4.py-3.flex.items-center.justify-end
                  button id="#{issue.id}-dropdown-button" class="inline-flex items-center p-0 5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" data-dropdown-toggle="#{issue.id}-dropdown" type="button"
                    svg.w-5.h-5[aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"]
                      path[d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"]
                  div id="#{issue.id}-dropdown" class=" hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                    div class= "py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="#{issue.id}-dropdown-button"
                      = link_to 'Show', project_issue_path(@project, issue), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to 'Edit', edit_project_issue_path(@project, issue), class:"block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
                    .py-1
                      = link_to "Delete", '#', class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
  /Details_card
  = render partial: 'epics/show/details_card'