config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }
  resources :users, only: [:show, :index, :destroy ] do
    collection do
      post :invite
    end
  end
  root 'welcome#index'
  get 'home', to: 'pages#index' 
  resources :projects do
    resources :project_users, only: [:index, :destroy] do
      collection do
        post :invite
      end
    end
    resources :teams do
      resources :project_users, only: [:destroy]
    end
    resources :epics
    resources :issues
  end
end

app/views/layouts/_messages.html.slim
-if notice
  #alert-3.flex.items-center.p-4.m-4.text-green-800.rounded-lg.bg-green-50.dark:bg-gray-800.dark:text-green-400[role="alert"]
    svg.flex-shrink-0.w-4.h-4[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewbox="0 0 20 20"]
      path[d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"]
    .ml-3.text-sm.font-medium
      .notice
        = notice
    button.ml-auto.-mx-1.5.-my-1.5.bg-green-50.text-green-500.rounded-lg.focus:ring-2.focus:ring-green-400.p-1.5.hover:bg-green-200.inline-flex.items-center.justify-center.h-8.w-8.dark:bg-gray-800.dark:text-green-400.dark:hover:bg-gray-700[type="button" data-dismiss-target="#alert-3" aria-label="Close"]
      span.sr-only
        | Close
      svg.w-3.h-3[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 14 14"]
        path[stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"]

-if alert
  #alert-2.flex.items-center.p-4.m-4.text-red-800.rounded-lg.bg-red-50.dark:bg-gray-800.dark:text-red-400[role="alert"]
    svg.flex-shrink-0.w-4.h-4[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewbox="0 0 20 20"]
      path[d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"]
    .ml-3.text-sm.font-medium
      .alert
        = alert
    button.ml-auto.-mx-1.5.-my-1.5.bg-red-50.text-red-500.rounded-lg.focus:ring-2.focus:ring-red-400.p-1.5.hover:bg-red-200.inline-flex.items-center.justify-center.h-8.w-8.dark:bg-gray-800.dark:text-red-400.dark:hover:bg-gray-700[type="button" data-dismiss-target="#alert-2" aria-label="Close"]
      span.sr-only
        | Close
      svg.w-3.h-3[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 14 14"]
        path[stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"]

app/views/layouts/_navbar.html.slim
.antialiased.bg-gray-50.dark:bg-gray-900
  nav.bg-white.border-b.border-gray-200.dark:bg-gray-800.dark:border-gray-700.fixed.left-0.right-0.top-0.z-50
    .flex.flex-wrap.justify-between.items-center.px-4.py-2
      .flex.justify-start.items-center
        /sidebar button
        button.p-2.mr-2.text-gray-600.rounded-lg.cursor-pointer.md:hidden.hover:text-gray-900.hover:bg-gray-100.focus:bg-gray-100.dark:focus:bg-gray-700.focus:ring-2.focus:ring-gray-100.dark:focus:ring-gray-700.dark:text-gray-400.dark:hover:bg-gray-700.dark:hover:text-white[data-drawer-target="sidebar" data-drawer-toggle="sidebar" aria-controls="sidebar"]
          = image_tag('hamburger.svg', alt: 'Hamburger SVG')
        /logo button
        = link_to 'PmApp', '#', class: "self-center text-2xl font-semibold whitespace-nowrap dark:text-white"
      /navbar menu
      .hidden.md:flex.justify-center.item-center.space-x-1
        = link_to home_path, class:"#{sidebar_main_btn_css}" do
          = image_tag('home.svg', alt: 'Home SVG')
          .pl-2
            | Home
        = link_to projects_path, class:"#{sidebar_main_btn_css} pr-6" do
          = image_tag('projects.svg', alt: 'Projects SVG')
          .pl-2
            | Projects
        button(id="create_dropdown_btn" class="#{sidebar_main_btn_css}" type="button" data-dropdown-toggle="create_dropdown_btn1" aria-expanded="false")
          = image_tag('create.svg', alt: 'CREATE SVG')
          .pl-2
            | Create
        #create_dropdown_btn1.hidden.z-50.my-4.w-44.text-base.list-none.bg-white.rounded-xl.shadow.dark:bg-gray-700.dark:divide-gray-600
          ul.py-1.divide-y.divide-gray-100.dark:text-gray-300[aria-labelledby="create_dropdown_btn"]
            li
              = link_to 'New project', new_project_path, class: "#{navbar_user_dropdown_btn_css}"
            - if @project && !@project.new_record?
              li
                = link_to 'New epic', new_project_epic_path(@project), class: "#{navbar_user_dropdown_btn_css}"
              li
                = link_to 'New issue', new_project_issue_path(@project), class: "#{navbar_user_dropdown_btn_css}"
      / user dropdown menu button      
      - if current_user 
        button#user-menu-button.flex.mx-3.text-sm.rounded-full.md:mr-0[type="button" aria-expanded="false" data-dropdown-toggle="dropdown"]
          = image_tag('user_menu_btn.svg', alt: 'USER MENU BTN SVG')
        #dropdown.hidden.z-50.my-4.w-56.text-base.list-none.bg-white.rounded.divide-y.divide-gray-100.shadow.dark:bg-gray-700.dark:divide-gray-600.rounded-xl
          .py-3.px-4
            span.block.text-sm.font-semibold.text-gray-900.dark:text-white
              = current_user.full_name
            span.block.text-sm.text-gray-900.truncate.dark:text-white
              = current_user.email
          ul.py-1.dark:text-gray-300[aria-labelledby="dropdown"]
            li
              = link_to 'My profile', '#', class: "#{navbar_user_dropdown_btn_css}"
            li
              = link_to 'Account settings', edit_user_registration_path, class: "#{navbar_user_dropdown_btn_css}"
          ul.py-1.dark:text-gray-300[aria-labelledby="dropdown"]
            li
              = link_to "Logout", destroy_user_session_path, class: "#{navbar_user_dropdown_btn_css}", data: { "turbo-method": :delete }
    .flex.justify-center.border-t.border-gray-200.space-x-0.5.py-2.md:hidden
      = link_to home_path, class:"#{navbar_main_btn_css}" do
        = image_tag('home.svg', alt: 'Home SVG')
      = link_to projects_path, class:"#{navbar_main_btn_css}" do
        = image_tag('projects.svg', alt: 'Projects SVG')
      button(id="create_dropdown_btn" class="#{navbar_main_btn_css}" type="button" data-dropdown-toggle="create_dropdown" aria-expanded="false")
        = image_tag('create.svg', alt: 'CREATE SVG')
      #create_dropdown.hidden.z-50.my-4.w-44.text-base.list-none.bg-white.rounded-xl.shadow.dark:bg-gray-700.dark:divide-gray-600
        ul.py-1.divide-y.divide-gray-100.dark:text-gray-300[aria-labelledby="create_dropdown_btn"]
          li
            = link_to 'New project', new_project_path, class: "#{navbar_user_dropdown_btn_css}"
          - if @project && !@project.new_record?
            li
              = link_to 'New epic', new_project_epic_path(@project), class: "#{navbar_user_dropdown_btn_css}"
            li
              = link_to 'New issue', new_project_issue_path(@project), class: "#{navbar_user_dropdown_btn_css}"

app/views/layouts/_sidebar.html.slim
aside#sidebar.fixed.top-0.z-40.w-full.transition-transform.-translate-y-full.md:top-0.md:left-0.md:translate-y-0.md:w-64.md:pt-14.md:border.md:border-gray-200[aria-label="Sidebar"]
  .overflow-y-auto.pt-32.h-screen.md:pt-5.px-3.bg-white.dark:bg-gray-800
    .my-3
      -if @project
        = link_to @project.name, project_path(@project), class: "#{sidebar_title_btn_css}"
    .mt-6.pl-1.pb-2.border-b.border-gray-200.text-base.font-medium.text-gray-900.text-xs
      | Planning
    ul.space-y-1.mt-1.pt-1
      li = link_to '#', class:"#{sidebar_main_btn_css}" do
        = image_tag('backlog.svg', alt: 'Backlog SVG')
        .ml-4.mt-1
          | Backlog
      li = link_to '#', class:"#{sidebar_main_btn_css}" do
        = image_tag('sprints.svg', alt: 'Sprints SVG')
        .ml-4
          | Sprints
      -if @project
        li = link_to project_epics_path(@project), class:"#{sidebar_main_btn_css}" do
          = image_tag('epics.svg', alt: 'Epics SVG')
          .ml-4
            | Epics
        li = link_to project_issues_path(@project), class:"#{sidebar_main_btn_css}" do
          = image_tag('issues.svg', alt: 'Issues SVG')
          .ml-4
            | Issues     
    .mt-5.pl-1.pb-2.border-b.border-gray-200.text-base.font-medium.text-gray-900.text-xs
      | People
    ul.space-y-1.mt-1.pt-1
      - if @project
        li = link_to project_project_users_path(@project), class:"#{sidebar_main_btn_css}" do
          = image_tag('team.svg', alt: 'Team SVG')
          .ml-3
            | Project Members  
        li = link_to project_teams_path(@project), class:"#{sidebar_main_btn_css}" do
          = image_tag('team.svg', alt: 'Team SVG')
          .ml-3
            | Project Teams
      - else
        li = link_to users_path, class:"#{sidebar_main_btn_css}" do
          = image_tag('team.svg', alt: 'Team SVG')
          .ml-3
            | Members           


/ #sidebar.fixed.top-0.left-0.w-full.md:w-64.md:h-screen.pt-14.bg-white.md:border-r.border-gray-200.border-b.md:border-b-0.dark:bg-gray-800.dark:border-gray-700[aria-label="Sidebar"]

app/views/layouts/_toolbar.html.slim
.antialiased.bg-gray-50.dark:bg-gray-900
  nav.bg-white.border-b.border-gray-200.px-4.py-2.5.dark:bg-gray-800.dark:border-gray-700
    .flex.flex-wrap.justify-between.items-center
      .flex.justify-start.items-center
        a.flex.items-center.justify-between.mr-4[href="#"]
          / img.mr-3.h-8[src="#" alt="PmApp Logo"]
          span.self-center.text-2xl.font-semibold.whitespace-nowrap.dark:text-white
            | Toolbar
      .flex.items-center.lg:order-2
        button.flex.mx-3.text-sm.rounded-full.md:mr-0.focus:ring-4.focus:ring-gray-300.dark:focus:ring-gray-600[type="button" aria-expanded="false" data-dropdown-toggle="dropdown_toolbar"]
          span.sr-only
            | Open toolbar menu
          svg[width="24" height="24" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"]
            path[d="M6.48999 12H6.49999M12.5 12H12.51M18.5 12H18.51" stroke="#2F2F38" stroke-width="3" stroke-linecap="round"]
        #dropdown_toolbar.hidden.z-50.my-4.w-56.text-base.list-none.bg-white.rounded.divide-y.divide-gray-100.shadow.dark:bg-gray-700.dark:divide-gray-600.rounded-xl
          .py-3.px-4
            span.block.text-sm.font-semibold.text-gray-900.dark:text-white
              | Placeholder
            span.block.text-sm.text-gray-900.truncate.dark:text-white
              | Placeholder
          ul.py-1.text-gray-700.dark:text-gray-300[aria-labelledby="dropdown"]
            li = link_to 'Placeholder', '#', class: "block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
            li = link_to 'Placeholder', '#', class: "block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white"
          ul.py-1.text-gray-700.dark:text-gray-300[aria-labelledby="dropdown"]
            li
              = link_to "Placeholder", '#', class: "block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white", data: { "turbo-method": :delete }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/sidebar'%>

    <main class="md:ml-64 h-screen pt-5 md:pt-14 ">
      <div class="max-w-2xl m-auto">
        <%= render 'layouts/messages'%>
      </div>
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <main class="container mx-auto mt-28 px-5 flex-1">
      <%= yield %>
    </main>

    <%= render 'layouts/footer'%>

  </body>
</html>

app/views/layouts/project.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>

    <main class="mt-20 pt-5">
      <div class="max-w-2xl m-auto">
        <%= render 'layouts/messages'%>
      </div>
      <%= yield %>
    </main>
    
  </body>
</html>